return {
  medieval_tree = {
    description = "Harvestable timber stand",
    blocking = false,
    reclaimable = true,
    reclaimTime = 10,
    damage = 1000,
    footprintX = 2,
    footprintZ = 2,
    object = "0ad/medieval_infantry.obj",
    customparams = { resource = "wood", capacity = 500 },
  },
  medieval_stone = {
    description = "Harvestable stone outcrop",
    blocking = false,
    reclaimable = true,
    reclaimTime = 10,
    damage = 1000,
    footprintX = 2,
    footprintZ = 2,
    object = "0ad/medieval_infantry.obj",
    customparams = { resource = "stone", capacity = 400 },
  },
  medieval_iron = {
    description = "Harvestable iron vein",
    blocking = false,
    reclaimable = true,
    reclaimTime = 10,
    damage = 1000,
    footprintX = 2,
    footprintZ = 2,
    object = "0ad/medieval_infantry.obj",
    customparams = { resource = "iron", capacity = 300 },
  },
  medieval_deer = {
    description = "Huntable deer herd",
    blocking = false,
    reclaimable = true,
    reclaimTime = 10,
    damage = 1000,
    footprintX = 2,
    footprintZ = 2,
    object = "0ad/medieval_infantry.obj",
    customparams = { resource = "food", capacity = 250 },
  },
}
