return {
  medieval_tree = {
    description = "Harvestable timber stand",
    blocking = false,
    reclaimable = true,
    reclaimTime = 10,
    damage = 1000,
    footprintX = 2,
    footprintZ = 2,
    object = "0ad/medieval_infantry.obj",
    customparams = { resource = "wood", capacity = 500 },
  },
  medieval_stone = {
    description = "Harvestable stone outcrop",
    blocking = false,
    reclaimable = true,
    reclaimTime = 10,
    damage = 1000,
    footprintX = 2,
    footprintZ = 2,
    object = "0ad/medieval_infantry.obj",
    customparams = { resource = "stone", capacity = 400 },
  },
  medieval_iron = {
    description = "Harvestable iron vein",
    blocking = false,
    reclaimable = true,
    reclaimTime = 10,
    damage = 1000,
    footprintX = 2,
    footprintZ = 2,
    object = "0ad/medieval_infantry.obj",
    customparams = { resource = "iron", capacity = 300 },
  },
  medieval_road = {
    name = "Medieval Dirt Road",
    description = "Medieval Dirt Road",
    blocking = false,
    crushable = false,
    -- Roads must be destructable so combat can cut supply by removing a road
    -- (Slice 7 "restoration after road removal"); `destructable = false` also
    -- made Spring.DestroyFeature a no-op in the probe.
    destructable = true,
    footprintX = 2,
    footprintZ = 2,
    object = "0ad/medieval_infantry.obj",
    customparams = { resource_cost_wood = 5, resource_cost_stone = 2 },
  },
  medieval_deer = {
    description = "Huntable deer herd",
    blocking = false,
    reclaimable = true,
    reclaimTime = 10,
    damage = 1000,
    footprintX = 2,
    footprintZ = 2,
    object = "0ad/medieval_infantry.obj",
    customparams = { resource = "food", capacity = 250 },
  },
}
