return {
  noweapon = {
    name = "Placeholder Weapon",
    weaponType = "Cannon",
    range = 0,
    reloadtime = 0,
    turret = false,
    damage = {default = 0},
  },
  sword = {
    name = "Broadsword",
    weaponType = "Melee",
    range = 45,
    reloadtime = 1.2,
    turret = false,
    damage = {default = 150},
    areaOfEffect = 8,
    craterBoost = 0,
    craterMult = 0,
    waterWeapon = true,
  },
  longbow = {
    name = "Longbow",
    weaponType = "Cannon",
    range = 380,
    reloadtime = 2.0,
    turret = true,
    damage = {default = 90},
    areaOfEffect = 12,
    craterBoost = 0,
    craterMult = 0,
    weaponVelocity = 400,
    myGravity = 0.5,
    heightBoostFactor = 1.2,
  },
  lance = {
    name = "Heavy Lance",
    weaponType = "Melee",
    range = 55,
    reloadtime = 1.5,
    turret = false,
    damage = {default = 240},
    areaOfEffect = 16,
    craterBoost = 0,
    craterMult = 0,
    waterWeapon = true,
  },
}