return {
  medieval_granary = {
    name = "Granary",
    description = "Stores harvested crops; a dedicated food drop-off point.",
    category = "LAND",
    buildCostEnergy = 0,
    buildCostMetal = 50,
    builder = false,
    buildTime = 25,
    canMove = false,
    canAttack = false,
    canFight = false,
    canPatrol = false,
    canGuard = false,
    footprintX = 4,
    footprintZ = 4,
    maxDamage = 800,
    sightDistance = 300,
    mass = 300,
    upright = true,
    objectName = "0ad/medieval_infantry.obj",
    side = "MEDIEVAL",
    customparams = {
      model_author = "Medieval-BAR-TC",
      dropoff = true,
      dropoff_radius = 96,
      dropoff_resource = "food",
      resource_cost_wood = 50,
    },
  },
}