return {
  medieval_archer = {
    name = "Longbowman",
    description = "Ranged infantry firing ballistic arrows (Phase 1 prototype placeholder)",
    category = "LAND",
    buildCostEnergy = 0,
    buildCostMetal = 90,
    builder = false,
    buildTime = 40,
    canMove = true,
    canAttack = true,
    canFight = true,
    canPatrol = true,
    canGuard = true,
    movementclass = "BOT2",
    footprintX = 2,
    footprintZ = 2,
    maxDamage = 750,
    maxVelocity = 1.9,
    acceleration = 0.4,
    brakeRate = 0.4,
    turnRate = 900,
    sightDistance = 450,
    speed = 28,
    mass = 150,
    upright = true,
    objectName = "0ad/medieval_archer.obj",
    script = "medieval_archer.lua",
    side = "MEDIEVAL",
    customparams = {
      resource_cost_food = 25,
      resource_cost_wood = 30,
      resource_cost_stone = 5,
      resource_cost_iron = 2,
      model_author = "Medieval-BAR-TC",
      unitgroup = "weapon",
    },
    weapons = {
      {
        name = "longbow",
        mainDir = {0,0,1},
        maxAngleDif = 300,
        onlyTargetCategory = "LAND",
        -- FX placeholder (no audio/CEG assets exist in this repo yet):
        --   soundstart = "<arrow release sfx>", soundhit = "<arrow impact sfx>",
        --   explosionGenerator = "<arrow hit CEG>"
        -- Keep as comment until a sounds/ dir and CEG generator names exist.
      },
    },
  },
}