return {
  medieval_archer = {
    name = "Longbowman",
    description = "Ranged infantry firing ballistic arrows (Phase 1 prototype placeholder)",
    category = "LAND",
    buildCostEnergy = 0,
    buildCostMetal = 90,
    builder = false,
    buildTime = 40,
    canMove = true,
    movementclass = "BOT2",
    footprintX = 2,
    footprintZ = 2,
    maxDamage = 750,
    maxVelocity = 1.9,
    acceleration = 0.4,
    brakeRate = 0.4,
    steeringRate = 900,
    sightDistance = 450,
    speed = 28,
    mass = 150,
    upright = true,
    objectName = "0ad/medieval_archer.obj",
    script = "medieval_archer.lua",
    side = "MEDIEVAL",
    customparams = {
      model_author = "Medieval-BAR-TC",
      unitgroup = "weapon",
    },
    weapons = {
      {
        def = "LONGBOW",
        onlyTargetCategory = "LAND",
      },
    },
    weaponDefs = {
      LONGBOW = {
        name = "Longbow",
        areaOfEffect = 12,
        craterBoost = 0,
        craterMult = 0,
        damage = {
          default = 90,
        },
        range = 380,
        reloadtime = 2.0,
        turret = true,
        weaponType = "Cannon",
        weaponVelocity = 400,
        myGravity = 0.5,
        heightBoostFactor = 1.2,
      },
    },
  },
}