return {
  medieval_villager = {
    name = "Villager",
    description = "Hardworking peasant; harvests timber, stone, iron, and crops, and builds settlement structures.",
    category = "LAND",
    buildCostEnergy = 0,
    buildCostMetal = 50,
    builder = true,
    buildTime = 25,
    canMove = true,
    canAttack = false,
    canFight = false,
    canPatrol = true,
    canGuard = true,
    worker = true,
    workertime = 10,
    repairable = true,
    movementclass = "BOT2",
    footprintX = 2,
    footprintZ = 2,
    maxDamage = 450,
    maxVelocity = 1.8,
    acceleration = 0.4,
    brakeRate = 0.5,
    turnRate = 1100,
    sightDistance = 350,
    speed = 28,
    mass = 120,
    upright = true,
    objectName = "0ad/medieval_infantry.obj",
    script = "medieval_villager.lua",
    side = "MEDIEVAL",
    buildoptions = {
      "medieval_house",
      "medieval_granary",
      "medieval_lumber_camp",
    },
    customparams = {
      model_author = "Medieval-BAR-TC",
      unitgroup = "builder",
      carry_capacity = 10,
      harvest_rate = 2,
      resource_cost_food = 50,
      resource_cost_wood = 0,
      resource_cost_stone = 0,
      resource_cost_iron = 0,
    },
  },
}
