return {
  medieval_town_center = {
    name = "Town Center",
    description = "Seat of the settlement; a drop-off point for all resources and the source of new villagers.",
    category = "LAND",
    buildCostEnergy = 0,
    buildCostMetal = 300,
    builder = false,
    buildTime = 90,
    canMove = false,
    canAttack = false,
    canFight = false,
    canPatrol = false,
    canGuard = false,
    isFactory = true,
    movementclass = "BOT2",
    footprintX = 7,
    footprintZ = 7,
    maxDamage = 3000,
    yardspeed = 1.0,
    sightDistance = 500,
    mass = 1000,
    upright = true,
    objectName = "0ad/medieval_infantry.obj",
    side = "MEDIEVAL",
    buildoptions = {
      "medieval_villager",
    },
    customparams = {
      model_author = "Medieval-BAR-TC",
      dropoff = true,
      dropoff_radius = 128,
      pop_provided = 10,
    },
  },
}