return {
  medieval_tower = {
    name = "Watchtower",
    description = "Elevated watchtower providing long sight range over the surrounding area.",
    category = "LAND",
    buildCostEnergy = 0,
    buildCostMetal = 60,
    builder = false,
    buildTime = 60,
    canMove = false,
    canAttack = false,
    canFight = false,
    canPatrol = false,
    canGuard = false,
    footprintX = 3,
    footprintZ = 3,
    maxDamage = 1500,
    sightDistance = 600,
    mass = 500,
    upright = true,
    objectName = "0ad/medieval_archer.obj",
    side = "MEDIEVAL",
    customparams = {
      model_author = "Medieval-BAR-TC",
      resource_cost_wood = 20,
      resource_cost_stone = 50,
      armor_class = "fortification",
    },
  },
}