return {
  medieval_barracks = {
    name = "Barracks",
    description = "Trains melee infantry and archers for the settlement's defense.",
    category = "LAND",
    buildCostEnergy = 0,
    buildCostMetal = 150,
    builder = false,
    buildTime = 60,
    canMove = false,
    canAttack = false,
    canFight = false,
    canPatrol = false,
    canGuard = false,
    isFactory = true,
    footprintX = 6,
    footprintZ = 6,
    maxDamage = 2500,
    sightDistance = 400,
    mass = 800,
    upright = true,
    objectName = "0ad/medieval_infantry.obj",
    side = "MEDIEVAL",
    buildoptions = {
      "medieval_infantry",
      "medieval_archer",
    },
    customparams = {
      model_author = "Medieval-BAR-TC",
      resource_cost_wood = 150,
      resource_cost_stone = 100,
    },
  },
}