return {
  medieval_infantry = {
    name = "Man-at-Arms",
    description = "Heavy melee infantry equipped with sword and shield (Phase 1 prototype placeholder)",
    category = "LAND",
    buildCostEnergy = 0,
    buildCostMetal = 100,
    builder = false,
    buildTime = 45,
    canMove = true,
    canAttack = true,
    canFight = true,
    canPatrol = true,
    canGuard = true,
    movementclass = "BOT2",
    footprintX = 2,
    footprintZ = 2,
    maxDamage = 1200,
    maxVelocity = 2.1,
    acceleration = 0.5,
    brakeRate = 0.5,
    turnRate = 1000,
    sightDistance = 350,
    speed = 32,
    mass = 200,
    upright = true,
    objectName = "0ad/medieval_infantry.obj",
    script = "medieval_infantry.lua",
    side = "MEDIEVAL",
    customparams = {
      resource_cost_food = 30,
      resource_cost_wood = 20,
      resource_cost_stone = 10,
      resource_cost_iron = 5,
      model_author = "Medieval-BAR-TC",
      unitgroup = "weapon",
    },
    weapons = {
      {
        name = "sword",
        mainDir = {0,0,1},
        maxAngleDif = 300,
        onlyTargetCategory = "LAND",
      },
    },
  },
}
