return {
  medieval_house = {
    name = "Peasant House",
    description = "Provides residential living space for the settlement, supporting +5 population.",
    category = "LAND",
    buildCostEnergy = 0,
    buildCostMetal = 60,
    builder = false,
    buildTime = 30,
    canMove = false,
    canAttack = false,
    canFight = false,
    canPatrol = false,
    canGuard = false,
    footprintX = 4,
    footprintZ = 4,
    maxDamage = 800,
    sightDistance = 300,
    mass = 300,
    upright = true,
    objectName = "0ad/medieval_infantry.obj",
    side = "MEDIEVAL",
    customparams = {
      model_author = "Medieval-BAR-TC",
      pop_provided = 5,
      resource_cost_wood = 60,
    },
  },
}