return {
  medieval_cavalry = {
    name = "Knight",
    description = "Mounted heavy cavalry built for fast charges (Phase 1 prototype placeholder)",
    category = "LAND",
    buildCostEnergy = 0,
    buildCostMetal = 220,
    builder = false,
    buildTime = 60,
    canMove = true,
    canAttack = true,
    canFight = true,
    canPatrol = true,
    canGuard = true,
    movementclass = "TANK3",
    footprintX = 3,
    footprintZ = 3,
    maxDamage = 2200,
    maxVelocity = 3.6,
    acceleration = 0.8,
    brakeRate = 0.6,
    turnRate = 1200,
    sightDistance = 400,
    speed = 54,
    mass = 450,
    upright = false,
    objectName = "0ad/medieval_cavalry.obj",
    script = "medieval_cavalry.lua",
    side = "MEDIEVAL",
    customparams = {
      resource_cost_food = 50,
      resource_cost_wood = 20,
      resource_cost_stone = 20,
      resource_cost_iron = 25,
      model_author = "Medieval-BAR-TC",
      unitgroup = "weapon",
    },
    weapons = {
      {
        name = "lance",
        mainDir = {0,0,1},
        maxAngleDif = 300,
        onlyTargetCategory = "LAND",
      },
    },
  },
}
