return {
  medieval_blacksmith = {
    name = "Blacksmith",
    description = "Crafts equipment and arms for the settlement.",
    category = "LAND",
    buildCostEnergy = 0,
    buildCostMetal = 100,
    builder = false,
    buildTime = 50,
    canMove = false,
    canAttack = false,
    canFight = false,
    canPatrol = false,
    canGuard = false,
    isFactory = true,
    footprintX = 5,
    footprintZ = 5,
    maxDamage = 2000,
    sightDistance = 400,
    mass = 600,
    upright = true,
    objectName = "0ad/medieval_infantry.obj",
    side = "MEDIEVAL",
    buildoptions = {},
    customparams = {
      model_author = "Medieval-BAR-TC",
      resource_cost_wood = 100,
      resource_cost_stone = 150,
    },
  },
}