return {
  medieval_fletcher = {
    name = "Fletcher",
    description = "Crafts bows and arrows for the settlement's ranged troops.",
    category = "LAND",
    buildCostEnergy = 0,
    buildCostMetal = 80,
    builder = false,
    buildTime = 45,
    canMove = false,
    canAttack = false,
    canFight = false,
    canPatrol = false,
    canGuard = false,
    isFactory = true,
    footprintX = 4,
    footprintZ = 4,
    maxDamage = 1500,
    sightDistance = 400,
    mass = 450,
    upright = true,
    objectName = "0ad/medieval_infantry.obj",
    side = "MEDIEVAL",
    buildoptions = {},
    customparams = {
      crafting = "bow",
      resource_cost_wood = 80,
      resource_cost_iron = 20,
      model_author = "Medieval-BAR-TC",
    },
  },
}
